

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5432:5432"

  cache:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=CHANGE_ME
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - cache
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 12345678
      DB_NAME: postgres
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: CHANGE_ME

    ports:
      - "8080:8080"
    volumes:
      - ./configs:/application/configs:ro
    links:
      - db
      - cache
    restart: unless-stopped


volumes:
    db:
      driver: local
    cache:
      driver: local
